#!/usr/bin/env bash

count=0
disconnected="%{F#bd93f8}%{F-}"
disconnected2="%{F#bd93f8}%{F-}"
disconnected3="%{F#bd93f8}%{F-}"
wireless_connected="%{F#bd93f8}%{F-}"
ethernet_connected="%{F#bd93f8}%{F-}"

ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 25
        else
            echo "$wireless_connected" ; sleep 25
        fi
    else
        echo "$disconnected" ; sleep 0.5
        echo "$disconnected2" ; sleep 0.5
        echo "$disconnected3" ; sleep 0.5
    fi
done
